export const skills = [
  "HTML/CSS",
  "SASS",
  "JavaScript",
  "TypeScript",
  "GSAP",
  "React JS",
  // "Next JS",
  "Redux",
  // "Framer Motion",
  // "UI + UX",
  // "Figma",
  "Node JS",
  "Express",
  "Mongo DB",
  "Firebase",
];